### PR TITLE
Add openshift CQL examples

### PR DESCRIPTION
**Pull request by asmigala**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Thanks, I noticed that in the end you used a different image.. Problems with mine? Thank you!

**Comment by asmigala** [comment]
Yes, neither your image nor the official docker cassandra image can run in openshift, due the usual permissions issues.

**Comment by oscerd** [comment]
Let me merge this

**Comment by oscerd** [comment]
Thanks @asmigala

**Pull request merged**
